// presets.js
export const presets = {
    "Dimensões": ["area", "perimetro", "eixo_maior", "eixo_menor", "extensao", "redondidade", "compactidade"],
    "Forma": ["fator_forma_1", "fator_forma_2", "fator_forma_3", "fator_forma_4"],
    "Coloração": ["RR_all", "RG_all", "RB_all"],
    "all_atributes": [    "area",
      "perimetro",
      "eixo_maior",
      "eixo_menor",
      "excentricidade",
      "eqdiasq",
      "solidez",
      "area_convexa",
      "extensao",
      "proporcao",
      "redondidade",
      "compactidade",
      "fator_forma_1",
      "fator_forma_2",
      "fator_forma_3",
      "fator_forma_4",
      "RR_media",
      "RG_media",
      "RB_media",
      "RR_dev",
      "RG_dev",
      "RB_dev",
      "RR_inclinacao",
      "RG_inclinacao",
      "RB_inclinacao",
      "RR_curtose",
      "RG_curtose",
      "RB_curtose",
      "RR_entropia",
      "RG_entropia",
      "RB_entropia",
      "RR_all",
      "RG_all",
      "RB_all"]
  };
  